### ISSUE TITLE
iOS volume very low (sound is coming from earpiece)

### ISSUE THREAD

**Issue by lijinshanmx** [bluefireteam/audioplayers#1194]
Android device is ok, but volume is very low on ios (xsmax os version: 15.5). I see some same issue, but close with 1.0.0-rc4 fix. now i am use 1.0.1.

**Comment by AldanisVigo** [comment]
It's not the volume. I figured out that it's not playing out of the speaker properly like it's supposed to. Instead it's playing out of the earpiece. I tried setting the audio context like this

 `
    AudioContextAndroid androidContext = AudioContextAndroid(
      isSpeakerphoneOn: true, 
      stayAwake: true, 
      contentType: AndroidContentType.music, 
      usageType: AndroidUsageType.media,
      audioFocus: AndroidAudioFocus.gain);
`
 `   AudioContextIOS iosContext = AudioContextIOS(
      category: AVAudioSessionCategory.ambient,
      defaultToSpeaker: true,
      options: [
        AVAudioSessionOptions.defaultToSpeaker,
        AVAudioSessionOptions.allowBluetooth,
        AVAudioSessionOptions.allowBluetoothA2DP
      ]
    );
`
`
    player.play(UrlSource(_currentSong!.downloadUrl),volume: 1.0,ctx: AudioContext(android: androidContext, iOS: iosContext),mode: PlayerMode.lowLatency);
   `

But it did not work on iOS. Still playing out of the earpiece.  Be careful bringing up the volume too much to compensate out of the earpiece and get a "speakerphone" effect as you may be overdriving the earpiece speaker. Any ideers?

**Comment by lijinshanmx** [comment]
Yes, you're right,it's really not playing out of the speaker。I turned the volume all the way up and the sound is still very low on ios。

**Comment by poupouneroot** [comment]
Hi , here same bug. The sound play into Ear speaker and won’t play in Bluetooth airpods and sound very low.

**Comment by DSoe** [comment]
I ran into the same issue. This is what I did to solve. I created AudioContext for iOS with defaultToSpeaker: false and set it in AudioPlayer.global.setGlobalAudioContext(_getAudioContext()). That solved my audio super quiet issue on my iPhone Xs Max.

**Comment by agordeev** [comment]
@DSoe it's unclear how `defaultToSpeaker: false` could help. Can you please add a code of `_getAudioContext()`?

@AldanisVigo can you please paste the working example of using `just_audio`? I found it even less friendly, and it plays from earpiece too.

**Comment by agordeev** [comment]
Ok, so this code worked for me:

```dart

      final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
          defaultToSpeaker: true,
          category: AVAudioSessionCategory.ambient,
          options: [
            AVAudioSessionOptions.defaultToSpeaker,
            AVAudioSessionOptions.mixWithOthers,
          ],
        ),
        android: AudioContextAndroid(
          isSpeakerphoneOn: true,
          stayAwake: true,
          contentType: AndroidContentType.sonification,
          usageType: AndroidUsageType.assistanceSonification,
          audioFocus: AndroidAudioFocus.none,
        ),
      );
      AudioPlayer.global.setGlobalAudioContext(audioContext);
```

**Comment by AldanisVigo** [comment]
> @DSoe it's unclear how `defaultToSpeaker: false` could help. Can you please add a code of `_getAudioContext()`?
> 
> @AldanisVigo can you please paste the working example of using `just_audio`? I found it even less friendly, and it plays from earpiece too.

`import 'package:just_audio/just_audio.dart' show AudioPlayer, AudioSource;`

Everything else is pretty much the same except for there's no Completion listener, but there is still a duration and position listener so whenerver position == duration it's the same thing as the completion listener if you need it. Hope that helps.

**Comment by DSoe** [comment]
> @DSoe it's unclear how `defaultToSpeaker: false` could help. Can you please add a code of `_getAudioContext()`?
> 
> @AldanisVigo can you please paste the working example of using `just_audio`? I found it even less friendly, and it plays from earpiece too.

This is what_getAudioContext() has.

`AudioContext _getAudioContext() {
    return AudioContext(
        android: AudioContextAndroid(
          isSpeakerphoneOn: false,
          stayAwake: true,
          contentType: AndroidContentType.music,
          usageType: AndroidUsageType.media,
          audioFocus: AndroidAudioFocus.gain,
        ),
        iOS: AudioContextIOS(
          defaultToSpeaker: false,
          category: AVAudioSessionCategory.playback,
          options: [AVAudioSessionOptions.mixWithOthers]
              + [AVAudioSessionOptions.allowAirPlay]
          + [AVAudioSessionOptions.allowBluetooth]
          + [AVAudioSessionOptions.allowBluetoothA2DP]
        )
    );
  }`

Since setting defaultToSpeaker: true works for you, I am thinking setting globalAudioContext somehow fixes the audio volume too low issue on iOS. I am not sure though.

**Comment by TSurridge** [comment]
I just had the same issue in a Flame Game (using FlameAudio) where on my iPhone I couldn't hear anything but it was working fine on my iPad.  I was going crazy trying to figure this out. Thought maybe something was wrong with my phone.  Tried it on my wife's phone same issue.  Ended up needed to add the same info above and now both iPhone and iPad have volume.

```
    if (!kIsWeb) {
      final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
          defaultToSpeaker: true,
          category: AVAudioSessionCategory.ambient,
          options: [
            AVAudioSessionOptions.defaultToSpeaker,
            AVAudioSessionOptions.mixWithOthers,
          ],
        ),
        android: AudioContextAndroid(
          isSpeakerphoneOn: true,
          stayAwake: true,
          contentType: AndroidContentType.sonification,
          usageType: AndroidUsageType.assistanceSonification,
          audioFocus: AndroidAudioFocus.none,
        ),
      );
          // NEEDED THIS audioContext or iPhone volume didn't work only BGM I could hardly hear
      AudioPlayer.global.setGlobalAudioContext(audioContext);
    }
```

**Comment by hgjinfan** [comment]
> this code worked for me
😊

**Comment by heynext** [comment]
> I just had the same issue in a Flame Game (using FlameAudio) where on my iPhone I couldn't hear anything but it was working fine on my iPad. I was going crazy trying to figure this out. Thought maybe something was wrong with my phone. Tried it on my wife's phone same issue. Ended up needed to add the same info above and now both iPhone and iPad have volume. I tried both AVAudioSessionCategory.ambient and AVAudioSessionCategory.playback and either worked. Pretty sure like others have said the key is **AVAudioSessionOptions.defaultToSpeaker**
> 
> ```
>     if (!kIsWeb) {
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>           // NEEDED THIS audioContext or iPhone volume didn't work only BGM I could hardly hear
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
>     }
> ```

It works!

**Comment by hatemragab** [comment]
> I just had the same issue in a Flame Game (using FlameAudio) where on my iPhone I couldn't hear anything but it was working fine on my iPad. I was going crazy trying to figure this out. Thought maybe something was wrong with my phone. Tried it on my wife's phone same issue. Ended up needed to add the same info above and now both iPhone and iPad have volume. I tried both AVAudioSessionCategory.ambient and AVAudioSessionCategory.playback and either worked. Pretty sure like others have said the key is **AVAudioSessionOptions.defaultToSpeaker**
> 
> ```
>     if (!kIsWeb) {
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>           // NEEDED THIS audioContext or iPhone volume didn't work only BGM I could hardly hear
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
>     }
> ```

Not working on all devices how to fix?

**Comment by spydon** [comment]
If anyone wants to put up a PR for this it would be greatly appreciated (I don't have any Apple devices to properly test this with).

**Comment by tozu** [comment]
Hi!
I would be interested looking into fixing this issue :)

**Comment by Gustl22** [comment]
Hi @tozu, you're welcome. Just start a Merge Request, if you feeling ready :)

**Comment by yoer** [comment]
`
    final AudioContext audioContext = AudioContext(
      iOS: AudioContextIOS(
        defaultToSpeaker: true,
        category: AVAudioSessionCategory.ambient,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.music,
        usageType: AndroidUsageType.media,
        audioFocus: AndroidAudioFocus.gain,
      ),
    );
    AudioPlayer.global.setGlobalAudioContext(audioContext);
`
this is work to me

**Comment by yoer** [comment]
> Ok, so this code worked for me:
> 
> ```dart
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
> ```

```dart

    final AudioContext audioContext = AudioContext(
      iOS: AudioContextIOS(
        defaultToSpeaker: true,
        category: AVAudioSessionCategory.ambient,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.music,  // i change this
        usageType: AndroidUsageType.media,  // i change this
        audioFocus: AndroidAudioFocus.gain,  // i change this
      ),
    );
    AudioPlayer.global.setGlobalAudioContext(audioContext);
```

i change some android config, and work

**Comment by adnanatif** [comment]
@agordeev  thanks this save my day

**Comment by iksent** [comment]
Worked for me with this config only on iOS:

```
iOS: AudioContextIOS(
  defaultToSpeaker: true,
  category: AVAudioSessionCategory.playAndRecord,
  options: [
    AVAudioSessionOptions.defaultToSpeaker,
    AVAudioSessionOptions.mixWithOthers,
  ],
)
```

**Comment by OHeroJ** [comment]
android  has same issue

**Comment by spydon** [comment]
> android  has same issue

As far as I know, Android does not have this issue, the sound is coming from the speaker and not from the earpiece by default on android.

**Comment by OHeroJ** [comment]
> 

Set the phone volume to 0, still can play out the sound; set the phone volume to the maximum, but the sound played out is still the original size

**Comment by utkarsh1097** [comment]
Found this in the SwiftAudioplayersDarwinPlugin definition. I think it will be useful to update the documentation accordingly. Or let the Flutter wrapper also mention this in logs

![image](https://user-images.githubusercontent.com/20616980/204117081-dc87eaa2-cabd-4ef0-b72a-98195343ef68.png)

**Comment by spydon** [comment]
Good catch @utkarsh1097!

**Comment by wjeanvilma** [comment]
> Ok, so this code worked for me:
> 
> ```dart
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
> ```

That works for me!

The only change for iOS is 'category: AVAudioSessionCategory.playAndRecord' instead of 'category: AVAudioSessionCategory.ambient'

**Comment by victormanuelfrancodev** [comment]
sorry, thank you for the answer, but I want to know Why before worked without that setting , I mean before I don't needed set all that 
is it for iOS update? 
```
      final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
          defaultToSpeaker: true,
          category: AVAudioSessionCategory.ambient,
          options: [
            AVAudioSessionOptions.defaultToSpeaker,
            AVAudioSessionOptions.mixWithOthers,
          ],
        ),
        android: AudioContextAndroid(
          isSpeakerphoneOn: true,
          stayAwake: true,
          contentType: AndroidContentType.sonification,
          usageType: AndroidUsageType.assistanceSonification,
          audioFocus: AndroidAudioFocus.none,
        ),
      );
      AudioPlayer.global.setGlobalAudioContext(audioContext);
```

**Comment by spydon** [comment]
> sorry, thank you for the answer, but I want to know Why before worked without that setting , I mean before I don't needed set all that is it for iOS update?

Previously you probably used an earlier version of AudioPlayers where his bug doesn't exist. 
It shouldn't be that hard to fix within AudioPlayers, and we are very open to PRs for it. It should be a pretty easy fix, but we don't have any iOS devices to test with.

**Comment by spydon** [comment]
@sameergoyal I think it was introduced in v1.0.0

**Comment by lukepighetti** [comment]
Sounds like this is a default configuration issue?

**Comment by spydon** [comment]
> Sounds like this is a default configuration issue?

It is indeed, and also `GlobalAudioContext` needs to be used for iOS instead.

**Comment by utkarsh1097** [comment]
> > Can you tell us what version was this bug introduced in, incase we want to revert back to a version where this didn't exist?

> I think it was introduced in v1.0.0

It was a breaking change (going from 0.x to 1.x) and not a "bug introduction". Plus, I would say its a matter of incomplete documentation. 

User can be let known via Flutter Docs that `AudioContext` is not supported for iOS, and to use `GlobalAudioContext` instead.

**Comment by spydon** [comment]
> It was a breaking change (going from 0.x to 1.x) and not a bug introduction. Plus, I would say its a matter of incomplete documentation.

It was a bug that was introduced, because the intended behavior is not that the sound is played from the earpiece by default, the default should be that it is played from the speaker.

> User can be let known via Flutter Docs that AudioContext is not supported for iOS, and to use GlobalAudioContext instead.

Agree, this should be added.

**Comment by dellumdeus** [comment]
> ```dart
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
> ```

Where did you place this code?

**Comment by spydon** [comment]
I just released AudioPlayers v1.2.0, can someone verify that this version resolves the issue?

**Comment by lukepighetti** [comment]
Issue is resolved on `audioplayers: 1.2.0` on iPhone 8+ running iOS `16.0.2`

**Comment by spydon** [comment]
> Issue is resolved on `audioplayers: 1.2.0` on iPhone 8+ running iOS `16.0.2`
> 
> Opened a PR to pump version on `flame_audio` [flame-engine/flame#2250](https://github.com/flame-engine/flame/pull/2250)

Super, thanks for checking and bumping `flame_audio`.

**Comment by sed1ka** [comment]
> I just released AudioPlayers v1.2.0, can someone verify that this version resolves the issue?

Unfortunately, last version didn't solve this issue.

**Comment by sed1ka** [comment]
> I just released AudioPlayers v1.2.0, can someone verify that this version resolves the issue?

I've used the last version, but unfortunately the issue still occurs I tried it on iPhone 7 plus running iOS 14.8.1

**Comment by spydon** [comment]
> I've used the last version, but unfortunately the issue still occurs I tried it on iPhone 7+ running iOS 14.8.1

And you have properly run `pub upgrade` etc? Seems strange that it would fix it on iOS 16, but not iOS 14.

**Comment by lukepighetti** [comment]
I just checked again and I think this is still broken.

I suspect what I did was "hot restart" instead of rebuilding the entire app when I went to check.

**Comment by spydon** [comment]
Alright, I'll reopen this again!

**Comment by tajaouart** [comment]
Even using setGlobalAudioContext as suggested above is no longer working.

**Comment by spydon** [comment]
> Even using setGlobalAudioContext as suggested above is no longer working.

That's odd, nothing should have changed about that.
Did you also use that work-around before @lukepighetti, and does it still work for you?

**Comment by lukepighetti** [comment]
This works as expected

```dart
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      iOS: AudioContextIOS(
        defaultToSpeaker: true,
        category: AVAudioSessionCategory.playAndRecord,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.sonification,
        usageType: AndroidUsageType.assistanceSonification,
        audioFocus: AndroidAudioFocus.none,
      ),
    ),
  );
```

**Comment by Gustl22** [comment]
@lukepighetti can you test, if it works with the following config?

```
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      iOS: AudioContextIOS(
        defaultToSpeaker: false,
        category: AVAudioSessionCategory.playback,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
      android: ...
      ),
    ),
  );
```

And if not can you also validate the variants for `category: AVAudioSessionCategory.playAndRecord` and `defaultToSpeaker: true`, but only one at a time.

My fear is that the option `defaultToSpeaker: false` does nothing. Or I didn't find usage in the native swift code. The relevant part is the option `AVAudioSessionOptions.defaultToSpeaker` which should also work with `AVAudioSessionCategory.playback`, `.ambient` and `.playAndRecord`.

**Comment by spydon** [comment]
@Gustl22 there is already a default config for each platform right? Just that the default config is wrong when it comes to iOS?

**Comment by Gustl22** [comment]
@spydon yes there is a default config but AudioConfig only has required parameters, so one needs to set both, if doing so.
I think so that the config is wrong (`AVAudioSessionOptions.defaultToSpeaker` is missing), but i cannot validate without an iphone :)

**Comment by spydon** [comment]
@Gustl22 makes sense, could you make a PR adding that? I'm sure someone in this thread could test it for us. :)

**Comment by OlegNovosad** [comment]
This context has proper volume values. Confirmed on iPhone X, iOS 16.0.2, `audioplayers: ^1.2.0`.

```dart
AudioContextIOS(
        defaultToSpeaker: true,
        category: AVAudioSessionCategory.playback,
        options: [
          AVAudioSessionOptions.defaultToSpeaker,
          AVAudioSessionOptions.mixWithOthers,
        ],
      ),
```

**Comment by OlegNovosad** [comment]
> > This context has proper volume values. Confirmed on iPhone X, iOS 16.0.2, `audioplayers: ^1.2.0`.
> > ```dart
> > AudioContextIOS(
> >         defaultToSpeaker: true,
> >         category: AVAudioSessionCategory.playback,
> >         options: [
> >           AVAudioSessionOptions.defaultToSpeaker,
> >           AVAudioSessionOptions.mixWithOthers,
> >         ],
> >       ),
> > ```
> 
> Thanks for confirming! Can you try without `defaultToSpeaker: true` set too?

The same behavior with either `true` or `false`.

**Comment by spydon** [comment]
Oh this closed automatically when the PR was merged I guess, but it should :tm: be fixed.
Can someone verify with audioplayers version 2.0.0?

**Comment by imaNNeoFighT** [comment]
> Oh this closed automatically when the PR was merged I guess, but it should ™️ be fixed. Can someone verify with audioplayers version 2.0.0?

It is not fixed. 
I tested it(`audioplayers: ^2.0.0`) on `iPhone 7 (14.4.2)`.

**Comment by Gustl22** [comment]
@imaNNeoFighT are you sure? Which code did you use? Can you recheck with our example app?

**Comment by imaNNeoFighT** [comment]
> @imaNNeoFighT thanks for your feedback. Which code did you use? Can you recheck with our example app? Are you interested in fixing this?

I used [this code](https://github.com/bluefireteam/audioplayers/issues/1194#issuecomment-1377337528). I didn't check the example app, but I will test it.
Yes, I am interested. What can I do?

**Comment by Gustl22** [comment]
@imaNNeoFighT Thank you! According to [this](https://github.com/bluefireteam/audioplayers/issues/1194#issuecomment-1377337528) it should work with `audioplayers: ^1.2.0`. If not we have to rethink what could have gone wrong generally.

Now with `audioplayers: ^2.0.0` this configuration should work theoretically:
```
  AudioPlayer.global.setGlobalAudioContext(
    AudioContext(
      iOS: AudioContextIOS(
        category: AVAudioSessionCategory.playback,
        options: const [
          AVAudioSessionOptions.mixWithOthers,
          AVAudioSessionOptions.defaultToSpeaker,
        ],
      ),
    ),
  );
```

or using the default values should also lead to that the sound is coming from loud speakers:
```
  AudioPlayer.global.setGlobalAudioContext(AudioContext());
```

If not something must have gone during this PR #1374. But I honestly don't know what.
You may can test the output in our [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example) app to make sure nothing else is responsible for something going wrong.

**Comment by imaNNeoFighT** [comment]
Okay, short answer: It works.

I was testing with AudioPlayer().**play**(source,  **ctx**); (instead of global configuration) 
None of the snippets that you gave me (a configured AudioContext with iOS, and an empty AudioContext constructor) work In this way (passing `AudioContext` to the `play()` function).
(It seems that configuration doesn't work in `play()` function. I think we need to file another issue to follow it up.

After that, I tried your exact code (configuring a global variable). It works both ways (configuring and empty constructor).

BTW `2.0.0` version doesn't work by default. I have to add the global config to fix this issue.

**Comment by Gustl22** [comment]
@imaNNeoFighT Thank you so much. That makes kind of sense as on ios, it is not possible to set a configuration for a single player. But we should either throw an error or instead for iOS set the global configuration silently (or with some log warning), if not setting globally.

I created #1396
Thank you, we can't really test as we don't have real devices! Doesn't really make sense to buy one only for this particular issue :/

**Comment by imaNNeoFighT** [comment]
Thank you (and other contributors) for developing this package.
It makes life easier for us :)
I hope to see the updated [flame_audio](https://pub.dev/packages/flame_audio) to use this new version.

**Comment by spydon** [comment]
@imaNNeo flame_audio is update too, if you missed it :)

**Comment by spydon** [comment]
This seems to still be an issue in 3.0.1 (the default is still the earpiece), just verified from Discord. 🥲

**Comment by Gustl22** [comment]
@spydon I already mentioned that in #1396 ;D

**Comment by spydon** [comment]
> @spydon I already mentioned that in #1396 ;D

I have such a short memory. :joy: 
But this should stay open and pinned then so that people find it when they have this problem.

**Comment by darajava** [comment]
> Ok, so this code worked for me:
> 
> ```dart
>       final AudioContext audioContext = AudioContext(
>         iOS: AudioContextIOS(
>           defaultToSpeaker: true,
>           category: AVAudioSessionCategory.ambient,
>           options: [
>             AVAudioSessionOptions.defaultToSpeaker,
>             AVAudioSessionOptions.mixWithOthers,
>           ],
>         ),
>         android: AudioContextAndroid(
>           isSpeakerphoneOn: true,
>           stayAwake: true,
>           contentType: AndroidContentType.sonification,
>           usageType: AndroidUsageType.assistanceSonification,
>           audioFocus: AndroidAudioFocus.none,
>         ),
>       );
>       AudioPlayer.global.setGlobalAudioContext(audioContext);
> ```

This works, but `AVAudioSessionCategory.ambient` causes the audio not to be played on iOS when the Ring/Silence switch is activated. `AVAudioSessionCategory.playback` is what I wanted.

**Comment by d-wire** [comment]
I've tried version `1.2.0`, and `3.0.1` on an iPhone 14 Pro running iOS `16.3.1` and I still can't get this to work. I'm doing
`void main() {
    final AudioContext audioContext = AudioContext(
        iOS: AudioContextIOS(
            defaultToSpeaker: true,
            category: AVAudioSessionCategory.playAndRecord,
            options: [
                AVAudioSessionOptions.defaultToSpeaker,
                AVAudioSessionOptions.mixWithOthers,
        ],
      ),
        android: AudioContextAndroid(
          isSpeakerphoneOn: true,
          stayAwake: true,
          contentType: AndroidContentType.music,
          usageType: AndroidUsageType.media,
          audioFocus: AndroidAudioFocus.gain,
        ),
      );
  AudioPlayer.global.setGlobalAudioContext(audioContext);
  
  runApp(const MyApp());
}`

I've tried all the different variations of iOS context category, but it's still not coming out of the speakers. What else might I be doing wrong?

**Comment by chloelamplugh** [comment]
> @imaNNeoFighT Thank you! According to [this](https://github.com/bluefireteam/audioplayers/issues/1194#issuecomment-1377337528) it should work with `audioplayers: ^1.2.0`. If not we have to rethink what could have gone wrong generally.
> 
> Now with `audioplayers: ^2.0.0` this configuration should work theoretically, so that the sound is coming from loud speakers:
> 
> ```
>   AudioPlayer.global.setGlobalAudioContext(
>     AudioContext(
>       iOS: AudioContextIOS(
>         category: AVAudioSessionCategory.playback,
>         options: const [
>           AVAudioSessionOptions.mixWithOthers,
>           AVAudioSessionOptions.defaultToSpeaker,
>         ],
>       ),
>     ),
>   );
> ```
> 
> or using the default values should also lead to the same behavior:
> 
> ```
>   AudioPlayer.global.setGlobalAudioContext(AudioContext());
> ```
> 
> If not something must have gone during this PR #1374. But I honestly don't know what. You may can test the output in our [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example) app to make sure nothing else is responsible for something going wrong.

For anyone who is confused about how to make this work, I added the "AudioPlayer.global.setGlobalAudioContext(AudioContext());" line in my 'init state'. See below: 

`  void initState() {
    super.initState();
    _audioPlayer = AudioPlayer();
    AudioPlayer.global.setGlobalAudioContext(const AudioContext());
    getURL();

    //Listen to states: playing, paused, stopped
    _audioPlayer.onPlayerStateChanged.listen((PlayerState state) {
      if (mounted) {
        // Check if the widget is still mounted
        setState(() {
          _playerState = state;
          _isPlaying = state == PlayerState.playing;
        });
      }
    });

    //Listen to audio duration
    _audioPlayer.onDurationChanged.listen((newDuration) {
      if (mounted) {
        // Check if the widget is still mounted
        setState(() {
          duration = newDuration;
        });
      }
    });

    //Listen to audio position
    _audioPlayer.onPositionChanged.listen((newPosition) {
      if (mounted) {
        // Check if the widget is still mounted
        setState(() {
          position = newPosition;
        });
      }
    });
  }`

**Comment by spydon** [comment]
Folks, can you try with the newly released AudioPlayers 4.0.0?
Hopefully this is solved now.

**Comment by skibos** [comment]
> Folks, can you try with the newly released AudioPlayers 4.0.0? Hopefully this is solved now.

I checked and after update to 4.0.1 it works perfect. Can be closed

**Comment by asmodeoux** [comment]
Hey guys, my issue is similar so I'll write my report/suggestion here. I use sound effects and a microphone at the same time in my app, and I noticed that if I set the category to **playAndRecord** the audio gets very quiet. It happens no matter what other options I choose, because basically the system wants to duck the audio to let the microphone record sound better.

The only way I found to fix it is to fork the lib and change the line which updates the category to:
`        try session.setCategory(category, mode: AVAudioSession.Mode.default, options: combinedOptions)
`

Once I use this **mode** parameter it gets fine. Is there any way the lib could support my case? Maybe there should be a Dart method to update iOS sound mode?

**Comment by spydon** [comment]
Hey @asmodeoux, this is not the same issue, please open a new one for your issue. :)

**Comment by Djihanegh** [comment]
still having the same issue : 
using **audioplayers: ^4.1.0**
Flutter version :  **3.10.2**

**Comment by spydon** [comment]
> still having the same issue : 
> using **audioplayers: ^4.1.0**
> Flutter version :  **3.10.2** 
> 
> ```dart
> final AudioContext audioContext = const AudioContext(
>     iOS: AudioContextIOS(
>       category: AVAudioSessionCategory.playAndRecord,
>       options: [
>         //  AVAudioSessionOptions.defaultToSpeaker,
>         AVAudioSessionOptions.allowAirPlay,
>         AVAudioSessionOptions.allowBluetooth,
>         AVAudioSessionOptions.allowBluetoothA2DP,
>         AVAudioSessionOptions.mixWithOthers,
>       ],
>     ),
>     android: AudioContextAndroid(
>       isSpeakerphoneOn: true,
>       stayAwake: true,
>       contentType: AndroidContentType.music,
>       usageType: AndroidUsageType.media,
>       audioFocus: AndroidAudioFocus.gain,
>     ),
>   );
> ```
> 
> ```dart
> @override
>   void initState() {
>     super.initState();
>     audioPlayer.setAudioContext(audioContext);
>   }
> ```

If you don't change the AudioContext at all, do you still have the same problem?

**Comment by Djihanegh** [comment]
> > still having the same issue :
> > using **audioplayers: ^4.1.0**
> > Flutter version :  **3.10.2**
> > ```dart
> > final AudioContext audioContext = const AudioContext(
> >     iOS: AudioContextIOS(
> >       category: AVAudioSessionCategory.playAndRecord,
> >       options: [
> >         //  AVAudioSessionOptions.defaultToSpeaker,
> >         AVAudioSessionOptions.allowAirPlay,
> >         AVAudioSessionOptions.allowBluetooth,
> >         AVAudioSessionOptions.allowBluetoothA2DP,
> >         AVAudioSessionOptions.mixWithOthers,
> >       ],
> >     ),
> >     android: AudioContextAndroid(
> >       isSpeakerphoneOn: true,
> >       stayAwake: true,
> >       contentType: AndroidContentType.music,
> >       usageType: AndroidUsageType.media,
> >       audioFocus: AndroidAudioFocus.gain,
> >     ),
> >   );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```dart
> > @override
> >   void initState() {
> >     super.initState();
> >     audioPlayer.setAudioContext(audioContext);
> >   }
> > ```
> 
> If you don't change the AudioContext at all, do you still have the same problem?

In the beginning I wasn't changing the AudioContext, and yes it was working like that, then I checked GitHub answers here, I tried to change the AudioContext and its still the same.

**Comment by spydon** [comment]
@Djihanegh can you post the content of your `pubspec.lock` file?

**Comment by MlecznyU** [comment]
Hi, 

I have been following this thread for some time. As soon as I saw that a fix had been merged, I immediately upgraded audioplayers to version 5.0.0.

Unfortunately, in the logs, I keep getting the same error for iOS. Regardless of the configuration, it is practically the same every time. The only change is when the `defaultToSpeaker` option is removed.

My configuration 
```
 const audioContext = AudioContext(
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.music,
        usageType: AndroidUsageType.assistanceSonification,
        audioFocus: AndroidAudioFocus.gain,
      ),
      iOS: AudioContextIOS(
        category: AVAudioSessionCategory.ambient,
        options: [
          AVAudioSessionOptions.allowBluetooth,
          AVAudioSessionOptions.allowBluetoothA2DP,
          AVAudioSessionOptions.defaultToSpeaker,
        ]
      )
    );
    AudioPlayer.global.setAudioContext(audioContext);
```
Error:

```
[as_client]     AVAudioSession_iOS.mm:2191  Error: category option 'defaultToSpeaker' is only applicable with category 'playAndRecord'
[as_client]     AVAudioSession_iOS.mm:2367  Failed to set category, error: -50
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(DarwinAudioError, Error configuring global audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
```

Without `defaultToSpeaker` option:

```
[as_client]     AVAudioSession_iOS.mm:2367  Failed to set category, error: -50
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(DarwinAudioError, Error configuring global audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>

```

And here is my pubspec.lock

```
  audioplayers:
    dependency: "direct main"
    description:
      name: audioplayers
      sha256: "2f4c0da9b483b45695d01dc738e1597d7137ae40fc2fa702f13ccc10efc706a2"
      url: "https://pub.dev"
    source: hosted
    version: "5.0.0"
  audioplayers_android:
    dependency: transitive
    description:
      name: audioplayers_android
      sha256: "7f18bb6c7de01684444e8cba577e3c3aee0ec379897f62ad4b8259d1e22f8c61"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  audioplayers_darwin:
    dependency: transitive
    description:
      name: audioplayers_darwin
      sha256: "80e341e6b2b364420516f2707271ec47f63b9b22766aa7f7d484601190c316a7"
      url: "https://pub.dev"
    source: hosted
    version: "5.0.0"
  audioplayers_linux:
    dependency: transitive
    description:
      name: audioplayers_linux
      sha256: cca3f272c7186dd2e0025b8864e1413ac5e081d74b17e28b02ceb2df4c110235
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  audioplayers_platform_interface:
    dependency: transitive
    description:
      name: audioplayers_platform_interface
      sha256: "47eae55e99ced11589998cf27e4eaabf5b475a7bd8bea7516ee6c2536a2e1abf"
      url: "https://pub.dev"
    source: hosted
    version: "6.0.0"
  audioplayers_web:
    dependency: transitive
    description:
      name: audioplayers_web
      sha256: "9f155590c6ba9ba469df637f4729264e4234dc3941ece4690dad63ffac19b5af"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  audioplayers_windows:
    dependency: transitive
    description:
      name: audioplayers_windows
      sha256: "8813b712ba919bb324bde5e3ba97edc81bface945953a54a3dea70b5608bcc70"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
```

**Comment by spydon** [comment]
@MlecznyU if you don't add any custom iOS context at all, do you still get the same problem?

**Comment by spydon** [comment]
> > @MlecznyU if you don't add any custom iOS context at all, do you still get the same problem?
> 
> No, error only occurs when custom context is provided.

Can't you just change the category from `ambient` to `playAndRecord` like it says in the error message then? 🤔

**Comment by MlecznyU** [comment]
> > > @MlecznyU if you don't add any custom iOS context at all, do you still get the same problem?
> > 
> > 
> > No, error only occurs when custom context is provided.
> 
> Can't you just change the category from `ambient` to `playAndRecord` like it says in the error message then? 🤔

I tested all `AVAudioSessionCategory` and each is giving me the same error

**Comment by spydon** [comment]
Alright, please open a new issue for this, since it is not the same issue as this one.

**Comment by anmollimje-mp** [comment]
final session = await AudioSession.instance;
    await session.configure(const AudioSessionConfiguration.music());

You can use this to make audio comming from Speaker

**Comment by j-ixcayau** [comment]
Hi @MlecznyU, for me the solution for this error was to just change the category to playAndRecord:

> Error:
> 
> ```
> [as_client]     AVAudioSession_iOS.mm:2191  Error: category option 'defaultToSpeaker' is only applicable with category 'playAndRecord'
> [as_client]     AVAudioSession_iOS.mm:2367  Failed to set category, error: -50
> flutter: ----------------FIREBASE CRASHLYTICS----------------
> flutter: PlatformException(DarwinAudioError, Error configuring global audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
> flutter: 
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
> #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
> <asynchronous suspension>
> ```
> 
> Without `defaultToSpeaker` option:
> 
> ```
> [as_client]     AVAudioSession_iOS.mm:2367  Failed to set category, error: -50
> flutter: ----------------FIREBASE CRASHLYTICS----------------
> flutter: PlatformException(DarwinAudioError, Error configuring global audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
> flutter: 
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
> #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
> <asynchronous suspension>
> ```


Like This:
```dart
static AudioContext get getContext => const AudioContext(
      iOS: AudioContextIOS(
        category: AVAudioSessionCategory.playAndRecord,
        options: [
          AVAudioSessionOptions.mixWithOthers,
          AVAudioSessionOptions.defaultToSpeaker,
        ],
      ),
      android: AudioContextAndroid(
        isSpeakerphoneOn: true,
        stayAwake: true,
        contentType: AndroidContentType.speech,
        usageType: AndroidUsageType.assistanceSonification,
        audioFocus: AndroidAudioFocus.gain,
      ),
    );
```

**Comment by fullflash** [comment]
According to Apple docs.
**defaultToSpeaker** 
You can set this option only when using the playAndRecord category. 

https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616462-defaulttospeaker

**Comment by asadbekdev** [comment]
> final session = await AudioSession.instance; await session.configure(const AudioSessionConfiguration.music());
> 
> You can use this to make audio comming from Speaker

Thanks bro! You SAVED ME!

**Comment by MyisCARRY** [comment]
I still got the issue on 6.0.0. None of the above solutions work for me.

**Comment by Gustl22** [comment]
@MyisCARRY can you plz open a new issue, where you also share your code to reproduce? This issue has been tackled and probably the error is somewhere else.
