### ISSUE TITLE
AudioPlayer._onPrepared Null check operator used on a null value problem

### ISSUE THREAD

**Issue by merterkoc** [bluefireteam/audioplayers#1640]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

l``Some users are receiving this error in our live application. This error occurs as a result of a null coming from the natived channel. We get this error on the same line on iOS and Android sides. We will open pr to solve this error.

```
Fatal Exception: FlutterError
Fatal Exception: FlutterError
0  App                            0x4b2973 AudioPlayer._onPrepared.<anonymous closure> (#2) + 128 (audioplayer.dart:128)
1  App                            0x593f3 Provider._inheritedElementOf + 343 (provider.dart:343)
2  App                            0x58e17 Provider.of + 293 (provider.dart:293)
3  App                            0x58d7b ReadContext.read + 649 (provider.dart:649)
4  App                            0x2739b3 WebViewState.build.<anonymous closure>.<anonymous closure> + 714 (add_credit_card.dart:714)
5  App                            0x57241b WebKitWebViewController._webView.<anonymous closure>.<anonymous closure> + 255 (webkit_webview_controller.dart:255)
``` 

### Expected behaviour

The function named "_onPrepared" of the "AudioPlayer" class should successfully process the data coming from the native channel and should not crash with any null value.

### Steps to reproduce

We tried to recreate it but I couldn't. However, this problem was seen in more than 400 users in versions 5.0.0 and 5.1.0.

### Affected platforms

Android, iOS

### Platform details

It's a platform and device independent bug. We get it on both platforms and a wide variety of devices. We get this error on iOS, Android and various devices.

### AudioPlayers Version

5.0.0, 5.1.0

### Build mode

debug, profile, release

### Audio Files/URLs/Sources

[masterpass_success.wav.zip](https://github.com/bluefireteam/audioplayers/files/12590801/masterpass_success.wav.zip)

### Working on PR

yeah

**Comment by Gustl22** [comment]
@merterkoc Are you sure it's the null value which is causing the error? Can you post a separate log for each platform? There's another issue regarding double fulfillment of the `preparedCompleter` but that's not the same thing.

**Comment by merterkoc** [comment]
I am sharing an example crash log.

[AudioPlayer onPrepared Crash Stacktrace.txt](https://github.com/bluefireteam/audioplayers/files/12831262/AudioPlayer.onPrepared.Crash.Stacktrace.txt)

![image](https://github.com/bluefireteam/audioplayers/assets/58307276/b4aebcc5-4261-4bdf-a52d-f3326f098cc2)

**Comment by Gustl22** [comment]
@merterkoc I cannot explain, how this bug could happen. I reevaluated the iOS platform multiple times on the native side. It would be really helpful, if you somehow can reproduce this bug. The thing is just removing the `null check operator` just hides the deeper problem on the lib or the native side, which maybe would then never be resolved. I saw you also have a `Logs` tab, maybe you can find out more about the actual error description instead of the Stacktrace :)

**Comment by tentenponce** [comment]
Hi, is there any update on this? There are 8.7k crash events affecting 6.3k users with this same error. Attaching our crash log as this might help identifying the issue. We cannot replicate it on our end as well.

[audioplayers-onprepared-crash.txt](https://github.com/bluefireteam/audioplayers/files/14752176/audioplayers-onprepared-crash.txt)

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown while finalizing the widget tree.
       at AudioPlayer._onPrepared.<fn>(audioplayer.dart:129)
       at Element.findAncestorWidgetOfExactType(framework.dart:4635)
       at StackRouterScope.of(controller_scope.dart:108)
       at AutoRouter.of(auto_router.dart:82)
       at AutoRouterX.router(auto_router_x.dart:8)
       at _RejectJobViewState.dispose(job_bottom_sheet_view.dart:395)
......
```

**Comment by merterkoc** [comment]
In the last 30 days, there have been 68 bug reports for iOS and 11 for Android. This is a very low number compared to the number of users. But I must say the problem remains

**Comment by Gustl22** [comment]
@merterkoc if you have something reproducible I'm happy to help. Otherwise we cannot make sure the issue is resolved. Can you contact one of your users to reproduce the issue?

**Comment by Yaseendev** [comment]
I think the problem is here (Line 129 in audioplayers.dart):

Stream<bool> get _onPrepared => eventStream
      .where((event) => event.eventType == AudioEventType.prepared)
      .map((event) => event.isPrepared!);

"isPrepared" property here has a null value 

We can modify the code so that it returns false when its null like this:
(event) => event.isPrepared ?? false

**Comment by Gustl22** [comment]
@Yaseendev no that's not the solution. See https://github.com/bluefireteam/audioplayers/issues/1640#issuecomment-1751367875

If you can reproduce the problem, let me know, so we can fix it on the native platform.

**Comment by firgia** [comment]
Hi, any news here? I'm still getting the same issue. 
<img width="1143" alt="Screenshot 2024-10-08 at 12 47 32" src="https://github.com/user-attachments/assets/0855b5d6-bf0f-40ad-b8ee-174205083ef9">

 I'm using audioplayers: ^5.0.0, this is my AudioplayerService code:
```
import 'dart:async';

import 'package:audioplayers/audioplayers.dart';

class AudioPlayerService {
  late AudioPlayer audio;
  StreamController<PlayerState> playerStateStream;

  AudioPlayerService({
    required this.playerStateStream,
  }) {
    _createAudioPlayer();
  }

  Future<Duration?> getCurrentPosition() {
    return audio.getCurrentPosition();
  }

  Future<bool> play(
    String source, {
    double playbackRate = 1.0,
  }) async {
    await audio.setPlaybackRate(playbackRate);
    return audio
        .play(source.startsWith("http")
            ? UrlSource(source)
            : DeviceFileSource(source))
        .then((_) {
      _addPlayerStateChanged(PlayerState.playing);

      return true;
    }).catchError((_) async {
      _addPlayerStateChanged(PlayerState.stopped);
      return false;
    });
  }

  Future<void> stop() async {
    await audio.stop();
    _addPlayerStateChanged(PlayerState.stopped);
  }

  void _createAudioPlayer() {
    audio = AudioPlayer(playerId: DateTime.now().toIso8601String());
    audio.onPlayerStateChanged.listen((event) {
      _addPlayerStateChanged(event);
    });
  }

  void _addPlayerStateChanged(PlayerState playerState) {
    if (!playerStateStream.isClosed) {
      playerStateStream.sink.add(playerState);
    }
  }

  Future<void> dispose() => audio.dispose();
}

```

**Comment by igbenic** [comment]
Same here I'm getting "Null check operator used on a null value", at:

```dart
audioplayer.dart in AudioPlayer._onPrepared.<fn> at line 129 within audioplayers
provider.dart in Provider._inheritedElementOf at line 343 within provider
provider.dart in Provider.of at line 293 within provider
```

on some android devices.
